# Generated by Django 3.2 on 2021-04-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actor',
            new_name='ActorA',
        ),
        migrations.RenameModel(
            old_name='Movie',
            new_name='MovieA',
        ),
        migrations.AlterModelTable(
            name='actora',
            table='actors_a',
        ),
        migrations.AlterModelTable(
            name='moviea',
            table='movies_a',
        ),
    ]
