# Generated by Django 3.2 on 2021-04-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0002_auto_20210429_0755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActorA',
            new_name='Actor',
        ),
        migrations.RenameModel(
            old_name='MovieA',
            new_name='Movie',
        ),
        migrations.AlterModelTable(
            name='actor',
            table='actors',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
    ]
